#! /bin/bash

#АВТОСТАРТ
sxhkd &
numlockx &
nitrogen --restore &
polybar main &
picom --config ~/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
conky &

# Touchpad
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Tapping Enabled" 1
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Tapping Drag Enabled" 1
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput libinput Scroll Method Enable>
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Disable While Typing Enabled">
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Accel Speed" 0.6
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Scrolling Pixel Distance" 20
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Accel Profile Enabled" 1
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Natural Scrolling Enabled" 1
#xinput set-prop "ELAN0504:01 04F3:312B Touchpad" "libinput Middle Emulation Enabled" 1

#ВОРКСПЕЙСЫ
bspc monitor -d I II III IV

#РАМКИ И ГАПСЫ
bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНАЫ
bspc config presel_feedback_color "fd2e59"

#ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ
#bspc config window_gap $gap;
#bspc config top_padding -$(($gap+2))
#bspc config left_padding -$(($gap+2))
#bspc config right_padding -$(($gap+4))
#bspc config bottom_padding $(($PANEL_HEIGHT-$gap))

#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle	     false

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
bspc config automatic_scheme	spiral


#ПРАВИЛА ОКОН
bspc rule -a firefox state=tiling follow=off
bspc rule -a TelegramDesktop state=pseudo-tiling follow=off rectangle=600x800
bspc rule -a alacritty state=floating follow=on rectangle=600x400
